auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  log_format: json
  http_server_read_timeout: 40s
  http_server_write_timeout: 40s

common:
  instance_addr: 0.0.0.0
  path_prefix: /loki
  storage:
    azure:
      account_name: ${AZURE_ACCOUNT_NAME}
      account_key: ${AZURE_ACCOUNT_KEY}
      container_name: ${AZURE_CONTAINER}
      endpoint_suffix: blob.core.windows.net
  replication_factor: 2
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 2
    final_sleep: 15s
  chunk_encoding: snappy
  chunk_idle_period: 40m
  chunk_retain_period: 90s
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 2560MB
  concurrent_flushes: 40
  max_chunk_age: 2h30m
  flush_on_shutdown: true

distributor:
  ring:
    kvstore:
      store: inmemory

frontend:
  max_outstanding_per_tenant: 640
  compress_responses: true

query_scheduler:
  max_outstanding_requests_per_tenant: 640

querier:
  max_concurrent: 40
  tail_max_duration: 1h
  extra_query_delay: 0s

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: azure
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: azure
  rule_path: /tmp/scratch
  alertmanager_url: ${ALERTMANAGER_URL:-http://alertmanager:9093}
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_sharding: false

analytics:
  reporting_enabled: false

limits_config:
  ingestion_rate_mb: 160
  ingestion_burst_size_mb: 320
  max_streams_per_user: 60000
  max_line_size: 640KB
  max_entries_limit_per_query: 12000
  
  max_query_length: 12000h
  max_query_parallelism: 80
  max_query_series: 1200
  
  retention_period: 45d
  
  max_concurrent_tail_requests: 25
  max_cache_freshness_per_query: 11m
  
  reject_old_samples: true
  reject_old_samples_max_age: 360h
  
  creation_grace_period: 15m
  unordered_writes: true

compactor:
  working_directory: /tmp/loki/retention
  compaction_interval: 15m
  retention_enabled: true
  retention_delete_delay: 4h
  retention_delete_worker_count: 350
  delete_request_store: azure
  apply_retention_interval: 2h


storage_config:
  azure:
    account_name: ${AZURE_ACCOUNT_NAME}
    account_key: ${AZURE_ACCOUNT_KEY}
    container_name: ${AZURE_CONTAINER}
    endpoint_suffix: blob.core.windows.net
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    cache_ttl: 30h
    shared_store: azure

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 2560
      ttl: 75m
  write_dedupe_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 640
      ttl: 75m

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 1280
        ttl: 75m
  cache_results: true
  max_retries: 11
  split_queries_by_interval: 20h


tracing:
  enabled: false
